# Generated by Django 3.1.4 on 2021-08-08 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appikey', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clg', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=90)),
                ('salary', models.IntegerField()),
            ],
        ),
    ]
