# Generated by Django 3.1.4 on 2021-08-08 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appikey', '0002_school'),
    ]

    operations = [
        migrations.DeleteModel(
            name='School',
        ),
    ]
