# Generated by Django 3.1.4 on 2021-08-10 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appikey', '0005_exam'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Exam',
        ),
    ]
